version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    env_file:
      - .env
    command: >
      mlflow server
      --host 0.0.0.0
      --port ${MLFLOW_PORT}
      --backend-store-uri ${MLFLOW_BACKEND_URI}
      --default-artifact-root ${MLFLOW_ARTIFACT_ROOT}
    ports:
      - "${MLFLOW_PORT}:5001"
    volumes:
      # Persist the SQLite DB file in a local folder
      - ./mlflow_db:/mlflow_db
      # Persist artifacts locally
      - ./mlartifacts:/mlartifacts
    restart: unless-stopped
